name: services
dependencies:
  redstone: ">=0.5.16 <0.6.0"
  mustache4dart: ">=1.0.6 <2.0.0"
  redstone_mapper:
    git: git://github.com/kaendfinger/redstone_mapper.git
  redstone_mapper_mongo:
    git:
      url: git://github.com/kaendfinger/redstone_mapper_mongo.git
      ref: service
  redstone_web_socket: ">=0.0.1 <0.1.0"
  password_hasher: ">=0.2.0 <0.3.0"
  mailer: ">=0.8.12 <0.9.0"
  http: ">=0.11.1+1 <0.12.0"
  markd: ">=0.7.1 <0.8.0"
  googleapis: ">=0.3.0 <0.4.0"
  googleapis_auth: ">=0.1.1 <0.2.0"
dev_dependencies:
  unittest: ">=0.11.0+5 <0.12.0"