name: services
dependencies:
  cipher: ">=0.7.1 <0.8.0"
  googleapis: ">=0.6.1 <0.9.0"
  googleapis_auth: ">=0.2.0 <0.4.0"
  http: ">=0.11.1+1 <0.12.0"
  mailer: ">=0.8.12 <0.9.0"
  markd: ">=0.7.1 <0.8.0"
  mustache4dart: ">=1.0.6 <2.0.0"
  password_hasher: ">=0.2.0 <0.3.0"
  redstone: ">=0.6.0-beta.1+1 <0.7.0"
  redstone_mapper: ">=0.2.0-beta.1 <0.5.0"
  redstone_mapper_mongo: ">=0.2.0-beta.1 <0.5.0"
  redstone_web_socket: ">=0.1.0-beta.1 <0.5.0"
  shelf_static: ">=0.2.2 <0.3.0"
  yaml: ">=2.1.2 <3.0.0"
